apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-vault-pvc
  namespace: mimir
spec:
  accessModes:
    - ReadWriteMany
  volumeName: mimir-vault-nfs
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
