apiVersion: v1
kind: Service
metadata:
  name: mimir-db-svc
  namespace: mimir
  labels:
    app: mimir-db
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: mimir-db
  type: ClusterIP
