apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: mimir
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: searxng/searxng:2026.4.4-7adace694
          ports:
            - containerPort: 8080
          env:
            - name: FORCE_OWNERSHIP
              value: "false"
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: searxng-secret-key
                  key: secret_key
          volumeMounts:
            - name: searxng-config
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: searxng-config
          configMap:
            name: searxng
            items:
              - key: settings.yaml
                path: settings.yml
