"""remove action_type from pending_actions

Revision ID: 090d42d82b38
Revises: 6b5fe7e8f46a
Create Date: 2026-04-15 16:09:54.553174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "090d42d82b38"
down_revision: Union[str, Sequence[str], None] = "6b5fe7e8f46a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_actions", "action_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pending_actions",
        sa.Column(
            "action_type",
            postgresql.ENUM("tool_call", "memory_write", name="action_type"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
