"""extend_rss_digest

Revision ID: 629b7137cbbf
Revises: a598fa51c391
Create Date: 2026-06-12 19:31:53.640388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "629b7137cbbf"
down_revision: Union[str, Sequence[str], None] = "a598fa51c391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rss_digest_entries", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column(
        "rss_digest_entries",
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rss_digest_entries", sa.Column("interesting_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "rss_digest_entries", sa.Column("relevance_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rss_digest_entries", "relevance_score")
    op.drop_column("rss_digest_entries", "interesting_score")
    op.drop_column("rss_digest_entries", "tags")
    op.drop_column("rss_digest_entries", "summary")
    # ### end Alembic commands ###
