"""add_pending_actions

Revision ID: 6b5fe7e8f46a
Revises: d580fce053d3
Create Date: 2026-04-09 21:22:34.366520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b5fe7e8f46a"
down_revision: Union[str, Sequence[str], None] = "d580fce053d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_actions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "action_type",
            sa.Enum("tool_call", "memory_write", name="action_type", create_type=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "discussing",
                "completed",
                name="action_status",
                create_type=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("message_ts", sa.String(), nullable=False),
        sa.Column("thread_ts", sa.String(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("triggered_by", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeout_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["pending_actions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_actions")
    op.execute("DROP TYPE IF EXISTS action_status")
    op.execute("DROP TYPE IF EXISTS action_type")
    # ### end Alembic commands ###
