"""add health snapshots and analyses

Revision ID: a2f751b9a257
Revises: 629b7137cbbf
Create Date: 2026-06-12 21:05:05.223401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2f751b9a257"
down_revision: Union[str, Sequence[str], None] = "629b7137cbbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_analyses",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("analysis_md", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_start", name="health_analyses_week_start_key"),
    )
    op.create_index(
        "ix_health_analyses_week_start", "health_analyses", ["week_start"], unique=False
    )
    op.create_table(
        "health_snapshots",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("week_end", sa.Date(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_start", name="health_snapshots_week_start_key"),
    )
    op.create_index(
        "ix_health_snapshots_week_start",
        "health_snapshots",
        ["week_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_health_snapshots_week_start", table_name="health_snapshots")
    op.drop_table("health_snapshots")
    op.drop_index("ix_health_analyses_week_start", table_name="health_analyses")
    op.drop_table("health_analyses")
    # ### end Alembic commands ###
