"""clean up slack

Revision ID: a598fa51c391
Revises: bee68ba78cc3
Create Date: 2026-05-14 15:30:24.650451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a598fa51c391"
down_revision: Union[str, Sequence[str], None] = "bee68ba78cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pending_actions", "channel_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "pending_actions", "message_ts", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "rss_digest_entries",
        "slack_channel_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "rss_digest_entries",
        "slack_message_ts",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rss_digest_entries",
        "slack_message_ts",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "rss_digest_entries",
        "slack_channel_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "pending_actions", "message_ts", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "pending_actions", "channel_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
