"""add_rss_digest_entries

Revision ID: bee68ba78cc3
Revises: 090d42d82b38
Create Date: 2026-04-17 22:08:30.071313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee68ba78cc3'
down_revision: Union[str, Sequence[str], None] = '090d42d82b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_digest_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('miniflux_entry_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('feed_name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('digest_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('slack_channel_id', sa.String(), nullable=False),
    sa.Column('slack_message_ts', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rss_digest_entries_message_ts', 'rss_digest_entries', ['slack_message_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rss_digest_entries_message_ts', table_name='rss_digest_entries')
    op.drop_table('rss_digest_entries')
    # ### end Alembic commands ###
