"""remove slack columns

Revision ID: ea028b698a86
Revises: a2f751b9a257
Create Date: 2026-06-18 21:57:00.462102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea028b698a86"
down_revision: Union[str, Sequence[str], None] = "a2f751b9a257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rss_digest_entries_message_ts"), table_name="rss_digest_entries"
    )
    op.drop_column("rss_digest_entries", "slack_channel_id")
    op.drop_column("rss_digest_entries", "slack_message_ts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rss_digest_entries",
        sa.Column("slack_message_ts", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rss_digest_entries",
        sa.Column("slack_channel_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_rss_digest_entries_message_ts"),
        "rss_digest_entries",
        ["slack_message_ts"],
        unique=False,
    )
    # ### end Alembic commands ###
